### PR TITLE
feat: add deployment revisionHistoryLimit

### PR DESCRIPTION
**Pull request by PG2000**
- adds the deployments.spec.revisionHistoryLimit in the generated helm deployment file

### CODE REVIEW

**Comment by PG2000** [comment]
@arttor not sure how to extend the tests. Maybe you can give me a hint?

**Comment by arttor** [comment]
@PG2000 best option is to add `revisionHistoryLimit` to [test_data/k8s-operator-ci.yaml](https://github.com/arttor/helmify/blob/main/test_data/k8s-operator-ci.yaml). It will be used in e2e tests on CI. 

Can you also adjust [test_data/sample-app.yaml](https://github.com/arttor/helmify/blob/main/test_data/sample-app.yaml) and regenerate chart examples with `cat test_data/sample-app.yaml | go run ./cmd/helmify examples/app` command?

**Comment by PG2000** [comment]
@arttor thx for your help. I think it's done now

**Review by arttor — APPROVED** [review]

**Comment by arttor** [comment]
@PG2000 thank you for your contribution! The changes are available in [v0.4.8 release](https://github.com/arttor/helmify/releases/tag/v0.4.8).

**Pull request merged**
