### PR TITLE
feat:support daemonset

### PR DESCRIPTION
**Pull request by huangzixun123**
This PR implements support for Daemonset, which is pretty much the same as Deployments.

### CODE REVIEW

**Review by arttor — APPROVED** [review]
Looks good. Thank you for your contribution!

**Comment by huangzixun123** [comment]
Hi, i have received your email. Thanks!This is a auto-reply email.

**Comment by arttor** [comment]
@huangzixun123 your changes are available in [v0.3.11 release](https://github.com/arttor/helmify/releases/tag/v0.3.11)

**Comment by huangzixun123** [comment]
OK, Thank you！

**Pull request merged**
