### PR TITLE
Extract args as values

### PR DESCRIPTION
**Pull request by bigkevmcd**
This change extracts the args from a PodTemplate as values allowing configuring the passed-in parameters.

### CODE REVIEW

**Review by arttor — CHANGES_REQUESTED** [review]
Can you please regenerate chart examples with `cat test_data/sample-app.yaml | go run ./cmd/helmify examples/app` and `cat test_data/k8s-operator-kustomize.output | go run ./cmd/helmify examples/operator` and push changes to your branch?

**Comment by arttor** [comment]
Thank you for updating the examples, Template looks good but I've run it locally and got an incorrect indent after `helm template test ./examples/app`.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-myapp
...
spec:
  template:
    spec:
      containers:
      - args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=127.0.0.1:8080
          - --leader-elect
        command:
        - /manager
...
``` 

There also might be a problem with the indent for `Job` and `CronJob` which also use pod processor but needs a different indent.

**Comment by bigkevmcd** [comment]
@arttor I think that should work, rearranged the test and fixed the indent.

**Review by arttor — APPROVED** [review]

**Comment by arttor** [comment]
@bigkevmcd please fix lint error `ineffectual assignment to err (ineffassign)`. Github Action log doesn't show the line number but you can run [golang-ci lint](https://golangci-lint.run/) locally to check.

**Review by arttor — APPROVED** [review]

**Pull request merged**
