### PR TITLE
fix: missing env field in the env var template

### PR DESCRIPTION
**Pull request by RealAnna**

### CODE REVIEW

**Review by arttor — DISMISSED** [review]

**Comment by arttor** [comment]
@RealAnna i cannot merge PR because there are some conflicts. can you please check?

**Comment by arttor** [comment]
Sorry, still cannot merge. 
image

**Comment by RealAnna** [comment]
@arttor rebased! thanks for noticing

**Comment by arttor** [comment]
closed as duplicate to #86

**Pull request closed without merging**
