### PR TITLE
add blank space to make the template helper more readable

### PR DESCRIPTION
**Pull request by dontan001**
as title

### CODE REVIEW

**Comment by dontan001** [comment]
@arttor please have a look when get chance

**Comment by arttor** [comment]
@dontan001 `examples/` are generated automatically with helmify. They should represent the exact output of the program. This means that changes should be done in the code and then samples should be regenerated with
`cat test_data/sample-app.yaml | go run ./cmd/helmify examples/app` and `cat test_data/k8s-operator-kustomize.output | go run ./cmd/helmify examples/operator`. 
But I don't think that it is a good idea to change these templates because they [copied from helm](https://github.com/helm/helm/blob/main/pkg/chartutil/create.go#L426-L487)

**Comment by dontan001** [comment]
> @dontan001 `examples/` are generated automatically with helmify. They should represent the exact output of the program. This means that changes should be done in the code and then samples should be regenerated with `cat test_data/sample-app.yaml | go run ./cmd/helmify examples/app` and `cat test_data/k8s-operator-kustomize.output | go run ./cmd/helmify examples/operator`. But I don't think that it is a good idea to change these templates because they [copied from helm](https://github.com/helm/helm/blob/main/pkg/chartutil/create.go#L426-L487)

@arttor 
Thank you for sharing this and I see, but why we deleted the blank spaces after we copied this, as you can see there are blank spaces in [original definition](https://github.com/helm/helm/blob/main/pkg/chartutil/create.go#L426-L487)

As for my commits, there are 2 in the pull request
- [the first one](https://github.com/Kyligence/helmify/commit/2179803cdc01ff4045d01cfdd993b2fba0fbc414) is the source code change
- while [the other one](https://github.com/Kyligence/helmify/commit/61a68c18622bcc894ad406098e32171847542e93) is auto generated via the commands above as you mentioned
    - Currently we have to play one minor trick to make the auto generation work, otherwise the _helpers.tpl will not updated. This is due to the [if here](https://github.com/arttor/helmify/blob/main/pkg/helm/init.go#L133), and I opened issue #24  to track this

**Comment by arttor** [comment]
I see. Sorry, i've totally missed changes in `init.go`.

**Pull request merged**
